// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMdjo1DRKChQvfJXy65SZXHWUqEy8bwAQ',
    appId: '1:428474538029:web:6885a2407254fcba0ac0a4',
    messagingSenderId: '428474538029',
    projectId: 'trekverse-2',
    authDomain: 'trekverse-2.firebaseapp.com',
    storageBucket: 'trekverse-2.firebasestorage.app',
    measurementId: 'G-Z66HKJJ9GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ3qnCu_J-eBvAVCFFlir_GGh9WPFc9Gc',
    appId: '1:428474538029:android:259f0adf6096afd40ac0a4',
    messagingSenderId: '428474538029',
    projectId: 'trekverse-2',
    storageBucket: 'trekverse-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3GuIpxMcwrc29bGPQ0INwoqUnkSIEVc',
    appId: '1:428474538029:ios:58196290d742bdbd0ac0a4',
    messagingSenderId: '428474538029',
    projectId: 'trekverse-2',
    storageBucket: 'trekverse-2.firebasestorage.app',
    iosBundleId: 'com.trekverse.trekverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3GuIpxMcwrc29bGPQ0INwoqUnkSIEVc',
    appId: '1:428474538029:ios:58196290d742bdbd0ac0a4',
    messagingSenderId: '428474538029',
    projectId: 'trekverse-2',
    storageBucket: 'trekverse-2.firebasestorage.app',
    iosBundleId: 'com.trekverse.trekverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMdjo1DRKChQvfJXy65SZXHWUqEy8bwAQ',
    appId: '1:428474538029:web:df93baa5d139dba00ac0a4',
    messagingSenderId: '428474538029',
    projectId: 'trekverse-2',
    authDomain: 'trekverse-2.firebaseapp.com',
    storageBucket: 'trekverse-2.firebasestorage.app',
    measurementId: 'G-0MDQEJMT3M',
  );
}
